#!/bin/bash

####################
# casme2
# positive
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4  --result_video checkpoints_casme2_edge_attention/Positive_EP01_01f_asianFemale.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4  --result_video checkpoints_casme2_edge_attention/Positive_EP01_01f_westernMale.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4  --result_video checkpoints_casme2_edge_attention/Negative_EP19_06f_asianFemale.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4  --result_video checkpoints_casme2_edge_attention/Negative_EP19_06f_westernMale.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4  --result_video checkpoints_casme2_edge_attention/Surprise_EP01_13_asianFemale.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4  --result_video checkpoints_casme2_edge_attention/Surprise_EP01_13_westernMale.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale

# casme2 -> smic
# positive
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4  --result_video checkpoints_casme2_edge_attention/Positive_s3_po_05_asianFemale_CASME2SMIC.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4  --result_video checkpoints_casme2_edge_attention/Positive_s3_po_05_westernMale_CASME2SMIC.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4  --result_video checkpoints_casme2_edge_attention/Negative_s11_ne_02_asianFemale_CASME2SMIC.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4  --result_video checkpoints_casme2_edge_attention/Negative_s11_ne_02_westernMale_CASME2SMIC.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4  --result_video checkpoints_casme2_edge_attention/Surprise_s20_sur_01_asianFemale_CASME2SMIC.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4  --result_video checkpoints_casme2_edge_attention/Surprise_s20_sur_01_westernMale_CASME2SMIC.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale

# casme2 -> samm
# positive
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4  --result_video checkpoints_casme2_edge_attention/Positive_022_3_3_asianFemale_CASME2toSAMM.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4  --result_video checkpoints_casme2_edge_attention/Positive_022_3_3_westernMale_CASME2toSAMM.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4  --result_video checkpoints_casme2_edge_attention/Negative_018_3_1_asianFemale_CASME2toSAMM.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4  --result_video checkpoints_casme2_edge_attention/Negative_018_3_1_westernMale_CASME2toSAMM.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4  --result_video checkpoints_casme2_edge_attention/Surprise_007_7_1_asianFemale_CASME2toSAMM.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4  --result_video checkpoints_casme2_edge_attention/Surprise_007_7_1_westernMale_CASME2toSAMM.mp4 --checkpoint checkpoints_casme2_edge_attention/checkpoint.pth.tar --relative --adapt_scale

###################
# smic
# positive
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4  --result_video checkpoints_smic_edge_attention/Positive_s3_po_05_asianFemale_smic.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4  --result_video checkpoints_smic_edge_attention/Positive_s3_po_05_westernMale_smic.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4  --result_video checkpoints_smic_edge_attention/Negative_s11_ne_02_asianFemale_smic.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4  --result_video checkpoints_smic_edge_attention/Negative_s11_ne_02_westernMale_smic.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4  --result_video checkpoints_smic_edge_attention/Surprise_s20_sur_01_asianFemale_smic.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4  --result_video checkpoints_smic_edge_attention/Surprise_s20_sur_01_westernMale_smic.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale

# smic -> casme2
# positive
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4  --result_video checkpoints_casme2_edge_attention/Positive_EP01_01f_asianFemale_SMICtoCASME2.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4  --result_video checkpoints_casme2_edge_attention/Positive_EP01_01f_westernMale_SMICtoCASME2.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4  --result_video checkpoints_casme2_edge_attention/Negative_EP19_06f_asianFemale_SMICtoCASME2.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4  --result_video checkpoints_casme2_edge_attention/Negative_EP19_06f_westernMale_SMICtoCASME2.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4  --result_video checkpoints_casme2_edge_attention/Surprise_EP01_13_asianFemale_SMICtoCASME2.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4  --result_video checkpoints_casme2_edge_attention/Surprise_EP01_13_westernMale_SMICtoCASME2.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale

# smic -> samm
# positive
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4  --result_video checkpoints_samm_edge_attention/Positive_022_3_3_asianFemale_SMICtoSAMM.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4  --result_video checkpoints_samm_edge_attention/Positive_022_3_3_westernMale_SMICtoSAMM.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4  --result_video checkpoints_samm_edge_attention/Negative_018_3_1_asianFemale_SMICtoSAMM.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4  --result_video checkpoints_samm_edge_attention/Negative_018_3_1_westernMale_SMICtoSAMM.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4  --result_video checkpoints_samm_edge_attention/Surprise_007_7_1_asianFemale_SMICtoSAMM.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4  --result_video checkpoints_samm_edge_attention/Surprise_007_7_1_westernMale_SMICtoSAMM.mp4 --checkpoint checkpoints_smic_edge_attention/checkpoint.pth.tar --relative --adapt_scale


####################
## samm
# positive
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4  --result_video checkpoints_samm_edge_attention/Positive_022_3_3_asianFemale_SAMM.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale --cpu
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4  --result_video checkpoints_samm_edge_attention/Positive_022_3_3_westernMale_SAMM.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale --cpu
# negative
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4  --result_video checkpoints_samm_edge_attention/Negative_018_3_1_asianFemale_SAMM.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale --cpu
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4  --result_video checkpoints_samm_edge_attention/Negative_018_3_1_westernMale_SAMM.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale --cpu
# surprise
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4  --result_video checkpoints_samm_edge_attention/Surprise_007_7_1_asianFemale_SAMM.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale --cpu
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4  --result_video checkpoints_samm_edge_attention/Surprise_007_7_1_westernMale_SAMM.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale --cpu


# samm -> casme2
# positive
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4  --result_video checkpoints_samm_edge_attention/Positive_EP01_01f_asianFemale_SAMMtoCASME2.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4  --result_video checkpoints_samm_edge_attention/Positive_EP01_01f_westernMale_SAMMtoCASME2.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4  --result_video checkpoints_samm_edge_attention/Negative_EP19_06f_asianFemale_SAMMtoCASME2.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4  --result_video checkpoints_samm_edge_attention/Negative_EP19_06f_westernMale_SAMMtoCASME2.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4  --result_video checkpoints_samm_edge_attention/Surprise_EP01_13_asianFemale_SAMMtoCASME2.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4  --result_video checkpoints_samm_edge_attention/Surprise_EP01_13_westernMale_SAMMtoCASME2.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale

# samm -> smic
# positive
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4  --result_video checkpoints_samm_edge_attention/Positive_s3_po_05_asianFemale_SAMMtoSMIC.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4  --result_video checkpoints_samm_edge_attention/Positive_s3_po_05_westernMale_SAMMtoSMIC.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4  --result_video checkpoints_samm_edge_attention/Negative_s11_ne_02_asianFemale_SAMMtoSMIC.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4  --result_video checkpoints_samm_edge_attention/Negative_s11_ne_02_westernMale_SAMMtoSMIC.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_asianFemale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4  --result_video checkpoints_samm_edge_attention/Surprise_s20_sur_01_asianFemale_SAMMtoSMIC.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-edge-attention-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/target_template_face/normalized_westernMale.jpg --driving_video ../../../hdd/Data/Facial_Micro-Expression/MEGC2021_generation_video/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4  --result_video checkpoints_samm_edge_attention/Surprise_s20_sur_01_westernMale_SAMMtoSMIC.mp4 --checkpoint checkpoints_samm_edge_attention/checkpoint.pth.tar --relative --adapt_scale
